### ISSUE TITLE
prototypeのclass化

### ISSUE THREAD

**Issue by Tsunehiko511** [NCMBMania/ncmb-extend#6]
prototypeで拡張していますが、es6からclassが使えるようになったのでclassでの拡張方法もサンプルで用意していただけないでしょうか？
（NCMBはUnityで利用しており、C#での利用になれているのでclassで書いていただきたいです）

**Comment by goofmint** [comment]
元々のQueryがClassではないので、継承は使えないので無理ですね…。

**Comment by Tsunehiko511** [comment]
そうですか。コメントありがとうございます。
